### Here We will Learn about Arithematic Operation in NumPy Arrays

In [15]:
import numpy as np

array = np.random.rand(3,3,3)
print(f"Below is how Array Looks Like:\n\n{array}")

Below is how Array Looks Like:

[[[0.41155431 0.0417661  0.96712307]
  [0.24596123 0.31262994 0.08666462]
  [0.38735929 0.70100492 0.19098981]]

 [[0.64033452 0.57766945 0.60095236]
  [0.20589314 0.28736131 0.15221068]
  [0.60105793 0.86393515 0.79770663]]

 [[0.28143977 0.75645934 0.39729386]
  [0.80355176 0.76708253 0.73236131]
  [0.24131767 0.03704167 0.77773603]]]


In [ ]:
# Sum up All the values of the Array
total_sum = np.sum(array)
print(f"Sum of all of the values of the Array is: {total_sum}")

Sum of All of the values of the Array is: 12.866458395647893


In [19]:
# Sum up only values present in the level 1:

total_sum_level_1 = np.sum(array[1,:,:])
print(f"Sum of all values of level 1 in the Array is: {total_sum_level_1}")

Sum of all values of level 1 in the Array is: 4.727121166389694


In [20]:
# Sum of the last column of level 2 and 3
last_column_sum_level_2and3 = np.sum(array[1::, ::, -1])
print(f"Sum of last colum values of level 2 and 3 in the Array is: {last_column_sum_level_2and3}")

Sum of last colum values of level 2 and 3 in the Array is: 3.458260866970278


In [23]:
# Calculate the sum of the four corners of the array
corners_sum  = np.sum([array[0,0,0],array[0,0,-1],array[2,2,0],array[2,2,-1]])
print(f"Sum of corner values of the Array is: {corners_sum}")

Sum of corner values of the Array is: 2.3977310782152346


In [31]:
# Calculate the sum of the four corners of the array (Middle Layer only)
corner_sum_level1 = np.sum([array[1,0,0],array[1,0,-1], array[1,-1,0], array[1,-1,-1]])
# corner_sum_level1 = np.sum([array[1,::2,::2]]) ----> will only work of 3x3 array 
print(f"Sum of corner values of level 1 of the array is: {corner_sum_level1}")

Sum of corner values of level 1 of the array is: 2.640051433581654


In [34]:
# The Task:
#   Calculate the total sum of Level 1.
#   Subtract the very center value.


total_sum_level_1 = np.sum(array[1,:,:])
center_value = array[1,1,1]
print(f"Difference Between total sum of level 1 and center value: \n{total_sum_level_1-center_value}")

Difference Between total sum of level 1 and center value: 
4.439759855256547


In [ ]:
big_array = np.random.rand(10,10,10)
max_value = np.max(big_array)


address = np.unravel_index(np.argmax(big_array), big_array.shape)

print(f"The King of the Hill is: {max_value}")
print(f"Found at Layer/Row/Col: {address}")
print(f"Below is the array:\n{big_array}") 0.99486426  

The King of the Hill is: 0.994864262962731
Found at Layer/Row/Col: (np.int64(0), np.int64(6), np.int64(3))
Below is the array:
[[[0.35902554 0.23991577 0.11584363 0.97137432 0.24410072 0.2882286
   0.75300719 0.34712941 0.00218088 0.31998345]
  [0.12342524 0.49759436 0.00113887 0.96607326 0.06677173 0.3011721
   0.60145521 0.35928482 0.78699716 0.98182051]
  [0.40472597 0.9149644  0.81873301 0.50882945 0.05618017 0.72385119
   0.66020301 0.65748661 0.20333909 0.20249153]
  [0.24194368 0.18060836 0.0182263  0.06090136 0.51336838 0.78908396
   0.44540377 0.1203785  0.8946945  0.71257482]
  [0.74864364 0.080008   0.40404946 0.89650447 0.97130259 0.73703879
   0.94607543 0.76961649 0.78461682 0.9792398 ]
  [0.46762531 0.23381613 0.35047745 0.71928233 0.17495103 0.25162739
   0.3723165  0.29006052 0.56726664 0.37545961]
  [0.54699044 0.03551999 0.93975286 0.99486426 0.21544662 0.76747169
   0.56915276 0.72712856 0.96564825 0.24999665]
  [0.71742683 0.23347665 0.07722137 0.97435599 0.1649842

In [46]:
# The Task:
#    Flip your 10x10x10 big_array so that:
#    The layers are reversed.
#    The rows are reversed.
#    The columns are reversed.
#    Basically, the value at [0,0,0] should end up at [9,9,9].

reversed_array = big_array[::-1,::-1,::-1]
print(reversed_array)

if big_array[9,9,9] == reversed_array[0,0,0]:
    print("True")

[[[0.17599493 0.40787022 0.67580851 0.52163122 0.30922858 0.78649573
   0.46356334 0.23750883 0.94617192 0.51207521]
  [0.54595551 0.91803436 0.61182662 0.59403182 0.33192171 0.97710594
   0.11876345 0.30958806 0.42076257 0.07325873]
  [0.43385763 0.36405702 0.33290829 0.37184195 0.83045444 0.95797654
   0.91625069 0.21788981 0.20480282 0.7749933 ]
  [0.33725393 0.34365983 0.44871041 0.12912684 0.49987793 0.95392063
   0.61438139 0.65296712 0.24013906 0.32596797]
  [0.09507909 0.98937574 0.2616484  0.67050046 0.03432908 0.73562885
   0.48220626 0.52169409 0.1645641  0.89702481]
  [0.81890441 0.81749882 0.56761758 0.2027174  0.66573733 0.56440578
   0.64536351 0.85669351 0.87385896 0.76962315]
  [0.4056317  0.42408523 0.39324363 0.20691487 0.9371077  0.61665731
   0.67591003 0.66899784 0.18216219 0.67492689]
  [0.60404214 0.39486394 0.30798104 0.76831154 0.63768402 0.88294155
   0.4139589  0.7960655  0.86986896 0.9753905 ]
  [0.49482534 0.20913406 0.47722359 0.40776316 0.97675831 0.1665

In [ ]:
# The Final Boss Task:
#     Create a 3D array of shape (100, 100, 3) filled with zeros (a black 100x100 image).
#     Draw a White Square in the middle of it.
#     Specifically: Set all 3 color channels (index :) to 255 for the pixels from row 25 to 75 and column 25 to 75.
image = np.zeros(shape=(100, 100, 3))

image[25:75, 25:75, :] = 255
print(image)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
# The Task:
#   Reset your image to all zeros.
#   Paint a square from 25 to 75, but make it Solid Red.

reset_image = np.zeros(shape=(100,100,3))
reset_image[25:75, 25:75, 0] = 255
print(reset_image)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
