### Masking and Search+Rescue Problems Recap
    

In [2]:
import numpy as np

arr = np.random.randint(1,101, size=(3,3,3))
print(arr)


# Finding the Max Value Index
# Note that the argmax() will return the index of the maximum number in the array

max_val = arr.argmax()
print(max_val)

# Now converting this output privided by argmax() into a 3D shaped output to display (layer, row, column)

output = np.unravel_index(max_val , shape=(3,3,3))
print(output)

[[[ 6 41 42]
  [91  2  9]
  [ 3 24 90]]

 [[97 51 71]
  [ 9 57 89]
  [78 99 53]]

 [[13 46 88]
  [36 22 83]
  [29 86 58]]]
16
(np.int64(1), np.int64(2), np.int64(1))


In [3]:
# The Task:
#   Use your current 3x3x3 arr.
#   Create a Boolean Mask where the value is even (divisible by 2).
#   Hint: Use (arr % 2 == 0)
#   Use that mask to change all even numbers to 999


mask  = ((arr % 2 )== 0)
arr2 = arr.copy()
arr2[mask] = 999
print(arr2)

[[[999  41 999]
  [ 91 999   9]
  [  3 999 999]]

 [[ 97  51  71]
  [  9  57  89]
  [999  99  53]]

 [[ 13 999 999]
  [999 999  83]
  [ 29 999 999]]]


In [4]:
# The Task:
#   Use your same mask from the previous step.
#   Instead of changing the numbers where the mask is True, change the numbers where the mask is False (the odd numbers).
#   Set those odd numbers to -1.


mask = ~mask
arr2[mask] = -1
print(arr2)

[[[999  -1 999]
  [ -1 999  -1]
  [ -1 999 999]]

 [[ -1  -1  -1]
  [ -1  -1  -1]
  [999  -1  -1]]

 [[ -1 999 999]
  [999 999  -1]
  [ -1 999 999]]]


In [5]:
# The Task:
#   Start with your original random array (not the -1/999 one).
#   Create a new array called binary_cube.
#   In one line, use np.where() to set all even numbers to 1 and all odd numbers to 0.


binary_cube = np.where((arr%2==0), 1, 0)
print(binary_cube)

[[[1 0 1]
  [0 1 0]
  [0 1 1]]

 [[0 0 0]
  [0 0 0]
  [1 0 0]]

 [[0 1 1]
  [1 1 0]
  [0 1 1]]]


In [6]:
# Creating a Mask of arr using zeros and Ones (Recall)
# Creating Mask 1 for Even while Mask 2 for Odd  and 
# just want to get the data of the original array to be displayed in 0's and 1's



cube = arr.copy()
odd_mask = np.zeros(shape=(3,3,3), dtype=bool)
even_mask = (arr%2==0)
print(odd_mask)
print(even_mask)

[[[False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]]]
[[[ True False  True]
  [False  True False]
  [False  True  True]]

 [[False False False]
  [False False False]
  [ True False False]]

 [[False  True  True]
  [ True  True False]
  [False  True  True]]]


In [10]:
# The Task:
#   You have your even_mask (the one with the True and False values).
#   Create a third mask called corner_mask that is all False (use np.zeros((3,3,3), dtype=bool)).
#   Now, manually turn only the 8 corners of corner_mask to True.
#   
#   Hint: Use corner_mask[::2, ::2, ::2] = True
# 
#   The Big Move: Combine them! Find where the number is Even AND it is a Corner.
# 
#   The Logic:
#   final_mask = even_mask & corner_mask (The & means "Both must be True").
# 
#   Your Goal:
#   How many True values are left in your final_mask?
#   Use this final_mask to change those specific even-corner numbers in your cube to 888.


corner_mask = np.zeros(shape=(3,3,3), dtype=bool)
corner_mask[::2, ::2, ::2] = True
final_mask = even_mask & corner_mask
total_true = np.count_nonzero(final_mask)
print(total_true)

5


In [15]:
# The Task:
#   Create a new mask called either_mask.
#   Use the pipe symbol | (which means OR) to combine your even_mask and corner_mask.
#   The Logic: either_mask = even_mask | corner_mask
# Your Goal:
#   Predict: Will np.count_nonzero(either_mask) be higher or lower than your previous count of 5?
#   Use this either_mask to change those values to 777 in a fresh copy of your array.



either_mask = even_mask | corner_mask
if np.count_nonzero(either_mask) > total_true:
    print("either_mask is Greater than total_true")
else:
    print("either_mask is lesser than total_true")
    

fresh_copy = arr.copy()
fresh_copy[either_mask] = 777
print(fresh_copy)

either_mask is Greater than total_true
[[[777  41 777]
  [ 91 777   9]
  [777 777 777]]

 [[ 97  51  71]
  [  9  57  89]
  [777  99  53]]

 [[777 777 777]
  [777 777  83]
  [777 777 777]]]
