In [ ]:
import numpy as np

arr5x5 = np.arange(1,26).reshape(5,5)

middle_square_3x3 = arr5x5[1:4, 1:4]

print("Below is the Output 3x3 Grid:")
print(middle_square_3x3)

Below is the Output 3x3 Grid:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [12]:
# Extracting the top-left 2x2 grid 
top_left_2x2_grid = arr5x5[:2, :2] 
print("Below is the Output of Top Left 2x2 Grid:")
print(top_left_2x2_grid)


Below is the Output of Top Left 2x2 Grid:
[[1 2]
 [6 7]]


In [17]:
# Grab the 1st, 3rd, and 5th rows (index 0, 2, and 4) and all the columns.
step2_jump_grid = arr5x5[::2, :]
print("Below is the Output of only 1st, 3rd and 5th Row:")
print(step2_jump_grid)

Below is the Output of only 1st, 3rd and 5th Row:
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [18]:
#  Can you extract the four corners of your 5x5 grid into a new 2x2 array
corner_values = arr5x5[::4, ::4]
print(corner_values)

[[ 1  5]
 [21 25]]


In [27]:
#Border Values
myArr_5x5 = np.arange(1,26).reshape(5,5)

mask = np.ones((5,5), dtype=bool)

mask[1:4, 1:4] = False

border_values = myArr_5x5[mask]
print(border_values)

[ 1  2  3  4  5  6 10 11 15 16 20 21 22 23 24 25]


In [29]:
# Hollow Grid
 
hollow_grid = arr5x5.copy()
hollow_grid[1:4,1:4] = 0
print(hollow_grid)
 

[[ 1  2  3  4  5]
 [ 6  0  0  0 10]
 [11  0  0  0 15]
 [16  0  0  0 20]
 [21 22 23 24 25]]
