In [49]:
import numpy as np


# Task 1

# Create a 3D array named image with a shape of (3, 3, 3).
# Initialize it so that:
# The first "layer" (index 0) is all zeros (representing no Red).
# The second "layer" (index 1) is all ones (representing full Green).
# The third "layer" (index 2) is filled with the number 255 (representing full Blue).
# Bonus: Once created, use a NumPy attribute to confirm the total number of elements in the array is 27.
# How would you write the code to fill that third layer with 255 without typing the number 9 times?


# Set Layer 1 to Zeros
image = np.zeros((3,3,3), dtype=int)
# Set  Layer 2 to 1's
image[1] = 1
# Set the Layer 3 to 255's
image[2] = 255
print(image)
print(f"\n\nTotal Elements: {image.size}")
print(f"Total Elements in 3rd Layer: {image[2].size}")

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]]]


Total Elements: 27
Total Elements in 3rd Layer: 9


In [50]:
# Task 2

# Take the 3D array you just created (the 3x3x3 one)  
# Change the very center value of the middle layer (the layer of 1s) to the number 99.


image[1,1,1] = 99
print(image)

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  1   1   1]
  [  1  99   1]
  [  1   1   1]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]]]


In [51]:
# Task 3

# Change the first value (top-left) of every layer to the number 7.
image[:,0,0] = 7
print(image)

[[[  7   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  7   1   1]
  [  1  99   1]
  [  1   1   1]]

 [[  7 255 255]
  [255 255 255]
  [255 255 255]]]


In [52]:
# Task 4:
# In Layer 0 (the layer of zeros), change every other number in the middle row to the number 88.
# Specifically, you want Layer 0 to look like this:
# [[0, 0, 0], [88, 0, 88], [0, 0, 0]]


image[0,1,::2]=88
print(image)


[[[  7   0   0]
  [ 88   0  88]
  [  0   0   0]]

 [[  7   1   1]
  [  1  99   1]
  [  1   1   1]]

 [[  7 255 255]
  [255 255 255]
  [255 255 255]]]


In [54]:
# Task 5:

flipped_image = image[::-1, :,:]
print(flipped_image)

[[[  7 255 255]
  [255 255 255]
  [255 255 255]]

 [[  7   1   1]
  [  1  99   1]
  [  1   1   1]]

 [[  7   0   0]
  [ 88   0  88]
  [  0   0   0]]]


In [61]:
# Task 6


# Take your 3D image (which has 27 total elements) and transform it into a 2D matrix.

# Use the .reshape() method on your image array.
# Change it into a 2D shape that has 9 rows and 3 columns.
# Save it to a new variable called matrix_2d

reshaped_image = image.reshape(9,3)
print(f"Below is how my Reshaped Image Looks Like:\n {reshaped_image}")
print(f"\n\nShape of Reshaped Array: {reshaped_image.shape}")
print(f"Size of Reshaped Array: {reshaped_image.size}")
print(f"Dimention of Reshaped Array: {reshaped_image.ndim}")


Below is how my Reshaped Image Looks Like:
 [[  7   0   0]
 [ 88   0  88]
 [  0   0   0]
 [  7   1   1]
 [  1  99   1]
 [  1   1   1]
 [  7 255 255]
 [255 255 255]
 [255 255 255]]


Shape of Reshaped Array: (9, 3)
Size of Reshaped Array: 27
Dimention of Reshaped Array: 2


In [68]:
hotspots = np.zeros((3,3,3), dtype=bool)
print(hotspots)
print(image)

hotspots = image > 100
print(hotspots)

[[[False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]]]
[[[  7   0   0]
  [ 88   0  88]
  [  0   0   0]]

 [[  7   1   1]
  [  1  99   1]
  [  1   1   1]]

 [[  7 255 255]
  [255 255 255]
  [255 255 255]]]
[[[False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]]

 [[False  True  True]
  [ True  True  True]
  [ True  True  True]]]


In [69]:
# Task Only Fetch those values from image whose Mask (Reference Value) is marked True

values_found = image[hotspots]
print(values_found)

[255 255 255 255 255 255 255 255]


In [70]:
# This finds the coordinates of every True value in your mask
indexes = np.where(image > 100)
print(indexes)

(array([2, 2, 2, 2, 2, 2, 2, 2]), array([0, 0, 1, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2, 0, 1, 2]))


In [2]:
import numpy as np


# Creating a Numpy 3D array whith random values


image = np.random.randint(1,200,size=(3,3,3))


# Method 1:

# print(F"Initally Image Looks Like\n\n{image}")


# top_left = image[0,0,0]
# bottom_right = image[2,2,2]

# hold = top_left
# top_left = bottom_right
# bottom_right = hold

# image[0,0,0] = top_left
# image[2,2,2] = bottom_right

# print(F"\n\nAfter Swapping Image Looks Like\n\n{image}")
# print(image)


# Method 2:   (Recommended)
print(f"Initally Image Looks Like\n\n{image}")
image[0,0,0] ,image[2,2,2] = image[2,2,2] , image[0,0,0]
print(F"\n\nAfter Swapping Image Looks Like\n\n{image}")


Initally Image Looks Like

[[[ 23  22 129]
  [133 135  29]
  [  1 115 181]]

 [[  3  34  58]
  [ 12  84 117]
  [160  18  53]]

 [[132 104 139]
  [175 117  69]
  [ 69 102 153]]]


After Swapping Image Looks Like

[[[153  22 129]
  [133 135  29]
  [  1 115 181]]

 [[  3  34  58]
  [ 12  84 117]
  [160  18  53]]

 [[132 104 139]
  [175 117  69]
  [ 69 102  23]]]
