In [20]:
import numpy as np

# 1-Dimentional Array
print(f"\t\t\t\t\t1-Dimentional Array\n ")
arr1 = np.array([1,2,3,4,5,6])
print(f"Array 1: {arr1}")
print(f"Dimentions of Array 1: {arr1.ndim}")
print(f"Size of Array 1: {arr1.size}")
print(f"Shape of Array 1: {arr1.shape}")

print(f"\nArray Structure: \n")
for i in range(len(arr1)):
    print(f"arr1[{i}] = {arr1[i]}")

					1-Dimentional Array
 
Array 1: [1 2 3 4 5 6]
Dimentions of Array 1: 1
Size of Array 1: 6
Shape of Array 1: (6,)

Array Structure: 

arr1[0] = 1
arr1[1] = 2
arr1[2] = 3
arr1[3] = 4
arr1[4] = 5
arr1[5] = 6


In [21]:
# 2-Dimentional Array
print(f"\t\t\t\t\t2-Dimentional Array\n ")
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Array 2:\n\n {arr2}")
print(f"\nDimentions of Array 2: {arr2.ndim}")
print(f"Size of Array 2: {arr2.size}")
print(f"Shape of Array 2: {arr2.shape}")

print(f"\nArray Structure: \n")
for i in range(len(arr2)):
    for j in range(len(arr2[i])):
        print(f"arr2[{i},{j}] = {arr2[i][j]}")

					2-Dimentional Array
 
Array 2:

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Dimentions of Array 2: 2
Size of Array 2: 9
Shape of Array 2: (3, 3)

Array Structure: 

arr2[0,0] = 1
arr2[0,1] = 2
arr2[0,2] = 3
arr2[1,0] = 4
arr2[1,1] = 5
arr2[1,2] = 6
arr2[2,0] = 7
arr2[2,1] = 8
arr2[2,2] = 9


In [24]:
# 3-Dimentional Array
print(f"\t\t\t\t\t3-Dimentional Array\n ")
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(f"Array 3:\n\n {arr3}")
print(f"\nDimentions of Array 3: {arr3.ndim}")
print(f"Size of Array 3: {arr3.size}")
print(f"Shape of Array 3: {arr3.shape}")

print(f"\nArray Structure: \n")
for i in range(len(arr3)):
    for j in range(len(arr3[i])):
        for k in range(len(arr3[i][j])):
            print(f"arr3[{i},{j},{k}] = {arr3[i][j][k]}")

					3-Dimentional Array
 
Array 3:

 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

Dimentions of Array 3: 3
Size of Array 3: 27
Shape of Array 3: (3, 3, 3)

Array Structure: 

arr3[0,0,0] = 1
arr3[0,0,1] = 2
arr3[0,0,2] = 3
arr3[0,1,0] = 4
arr3[0,1,1] = 5
arr3[0,1,2] = 6
arr3[0,2,0] = 7
arr3[0,2,1] = 8
arr3[0,2,2] = 9
arr3[1,0,0] = 10
arr3[1,0,1] = 11
arr3[1,0,2] = 12
arr3[1,1,0] = 13
arr3[1,1,1] = 14
arr3[1,1,2] = 15
arr3[1,2,0] = 16
arr3[1,2,1] = 17
arr3[1,2,2] = 18
arr3[2,0,0] = 19
arr3[2,0,1] = 20
arr3[2,0,2] = 21
arr3[2,1,0] = 22
arr3[2,1,1] = 23
arr3[2,1,2] = 24
arr3[2,2,0] = 25
arr3[2,2,1] = 26
arr3[2,2,2] = 27


In [25]:
# 4-Dimentional Array
print(f"\t\t\t\t\t4-Dimentional Array\n ")
arr4 = np.array([[[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]],[[[28,29,30],[31,32,33],[34,35,36]],[[37,38,39],[40,41,42],[43,44,45]],[[46,47,48],[49,50,51],[52,53,54]]],[[[55,56,57],[58,59,60],[61,62,63]],[[64,56,66],[67,68,69],[70,71,72]],[[73,74,75],[76,77,78],[79,80,81]]]])
print(f"Array 4:\n\n {arr4}")
print(f"\nDimentions of Array 4: {arr4.ndim}")
print(f"Size of Array 4: {arr4.size}")
print(f"Shape of Array 4: {arr4.shape}")

print(f"\nArray Structure: \n")
for i in range(len(arr4)):
    for j in range(len(arr4[i])):
        for k in range(len(arr4[i][j])):
            for l in range(len(arr4[i][j][k])):
                print(f"arr4[{i},{j},{k},{l}] = {arr4[i][j][k][l]}")

					4-Dimentional Array
 
Array 4:

 [[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]
   [25 26 27]]]


 [[[28 29 30]
   [31 32 33]
   [34 35 36]]

  [[37 38 39]
   [40 41 42]
   [43 44 45]]

  [[46 47 48]
   [49 50 51]
   [52 53 54]]]


 [[[55 56 57]
   [58 59 60]
   [61 62 63]]

  [[64 56 66]
   [67 68 69]
   [70 71 72]]

  [[73 74 75]
   [76 77 78]
   [79 80 81]]]]

Dimentions of Array 4: 4
Size of Array 4: 81
Shape of Array 4: (3, 3, 3, 3)

Array Structure: 

arr4[0,0,0,0] = 1
arr4[0,0,0,1] = 2
arr4[0,0,0,2] = 3
arr4[0,0,1,0] = 4
arr4[0,0,1,1] = 5
arr4[0,0,1,2] = 6
arr4[0,0,2,0] = 7
arr4[0,0,2,1] = 8
arr4[0,0,2,2] = 9
arr4[0,1,0,0] = 10
arr4[0,1,0,1] = 11
arr4[0,1,0,2] = 12
arr4[0,1,1,0] = 13
arr4[0,1,1,1] = 14
arr4[0,1,1,2] = 15
arr4[0,1,2,0] = 16
arr4[0,1,2,1] = 17
arr4[0,1,2,2] = 18
arr4[0,2,0,0] = 19
arr4[0,2,0,1] = 20
arr4[0,2,0,2] = 21
arr4[0,2,1,0] = 22
arr4[0,2,1,1] = 23
arr4[0,2,1,2] = 24
arr4[0,2,2,0] = 2