# Broadcasting

In Simple, Broadcasting is basically NumPy’s way of making two different-sized arrays "match" so it can do math on them without you having to write a loop. 

Imagine you have a 3x3x3 cube and a 1x3 row. To add them, NumPy "stretches" (broadcasts) that single row to fill the entire cube. 

### The "Right-to-Left" Rule
NumPy compares the shapes of your arrays starting from the right side (the last dimension) and moving left. For each dimension, the sizes must either: 

    - Be equal.
    - One of them must be 1. 

### Visual Example
Let's look at your offsets challenge:
    - Array A (Cube): (3, 3, 3)
    - Array B (Row): ( 3) ---> NumPy treats this as (1, 1, 3) 

### How NumPy "Stretches" it:
    - Step 1: It sees the 3 at the end matches the 3 in the cube's columns.
    - Step 2: It "copies" the row [10, -5, 2] to fill all 3 rows of a layer.
    - Step 3: It "copies" that whole layer to fill all 3 depths of the cube. 

 
Now you have two 3x3x3 cubes, and NumPy just adds them element-by-element. 



In [31]:
import numpy as np 

# Initializing a 3x3x3 array with rach index set to zero
cube = np.zeros(shape=(3,3,3), dtype=int)

# Initializing an 1x3 array 
# Which will be stretched later on durinng broadcasting to match the size of the cube 
offset = np.array([10,20,30])

# Initail Cube 
print(f"Initially: \n\n{cube}")

# Broadcasting
cube += offset
# result =  cube + offset

# After Broadcasting
print(f"\nAfter Broadcasting: \n\n{cube}")
# print(f"\nAfter Broadcasting: \n\n{result}")




Initially: 

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]

After Broadcasting: 

[[[10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]]]


## Challange 2


That is a perfect implementation! Your code correctly demonstrates how NumPy handles the heavy lifting. By adding a 1D array (the offset) to a 3D array (the cube), you successfully triggered that "stretching" behavior without needing a single for loop.

Since the last dimension of your cube (3) matched the length of your offset (3), NumPy expanded those values across every row and every depth layer.

Ready for the next challenge to level up?

Challenge: Selective Stretching
Let’s see if you can control which dimension gets the values. Instead of adding [10, 20, 30] to every row, I want you to add a different value to each layer of the cube.

The Goal:
Create a 3x3x3 cube of zeros. Add an array so that:

* Layer 0 gets +10
* Layer 1 gets +20
* Layer 2 gets +30

(Hint: You'll need to change the shape of your offset array so it aligns with the first dimension instead of the last one.)
Do you want to try defining that offset shape to target the layers?


The Logic:
Your cube is shape (3, 3, 3).
To target the layers, your offset needs to be shaped like (3, 1, 1).

When NumPy compares them:
* Last dim: 1 matches 3 (Stretches across columns).
* Middle dim: 1 matches 3 (Stretches across rows).
* First dim: 3 matches 3 (Each value stays in its specific layer).

Your Task

Try to modify your previous code. Instead of a simple 1D array [10, 20, 30], you need to create a 3D column with those same values.




In [32]:
cube  = np.zeros(shape=(3,3,3), dtype=int)
layered_offset = np.array([[[10]],[[20]],[[30]]])
print(cube)
print(layered_offset)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[10]]

 [[20]]

 [[30]]]


In [33]:
print(cube.shape)
print(layered_offset.shape)

(3, 3, 3)
(3, 1, 1)


In [34]:
# Initail Cube 
print(f"Initially: \n\n{cube}")

# Broadcasting
cube += layered_offset

# After Broadcasting
print(f"\nAfter Broadcasting: \n\n{cube}")

Initially: 

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]

After Broadcasting: 

[[[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[20 20 20]
  [20 20 20]
  [20 20 20]]

 [[30 30 30]
  [30 30 30]
  [30 30 30]]]


## Ready for the "Advanced Slicer" Challenge?

Now that you can fill the cube, let's see if you can pull data out of it.

The Goal:
- Using your current "After Broadcasting" cube (where each layer has 10s, 20s, and 30s):
- Extract only the second layer (the one full of 20s).
- Extract the very first value of every layer (should give you [10, 20, 30]).

Hint:
* To get a whole layer, you use cube[index].
* To get a specific spot across all layers, you use a colon : like this: cube[:, row, col].

Do you want to try writing the indexing code to grab those specific parts?

In [35]:
layer_2_of_cube = cube[1,:,:]
print(layer_2_of_cube)

[[20 20 20]
 [20 20 20]
 [20 20 20]]


## The Last Piece of the Puzzle: The "All Layers" Slice

Now, let's try the second part of the challenge. Can you extract the very first value (top-left corner) from every layer at once?

The Goal:
- Get an array that looks like [10, 20, 30].

Hint:

Instead of picking one layer, use the colon : for the first dimension to say "give me all layers," and then specify the exact row and column index you want from each.

> How would you write that slice?

In [36]:
topLeft_value_of_every_layer = cube[:,0,0]
print(topLeft_value_of_every_layer)

[10 20 30]


## The "Shape-Shifter" Finale

Now that you can build, broadcast, and slice, let's try one last trick: Flattening and Transposing.

> The Challenge:
- Your cube is currently (3, 3, 3). Let's say you want to turn that 3D cube into one long 1D line of numbers.

>The Goal:
- Use a single NumPy method to turn your 27-element cube into a flat array and Print the result.

> Hint: 
- Look for a method that sounds like "making something level" or "flat" (e.g., .flatten() or .ravel()).


In [37]:
flattened_cube = cube.flatten()
print(flattened_cube)

# Their is another method --> ravel()   which can be used to convert the 3D array into a 1D array
raveled_cube = cube.ravel()
print(raveled_cube)

[10 10 10 10 10 10 10 10 10 20 20 20 20 20 20 20 20 20 30 30 30 30 30 30
 30 30 30]
[10 10 10 10 10 10 10 10 10 20 20 20 20 20 20 20 20 20 30 30 30 30 30 30
 30 30 30]


> Spot on! You’ve got the output and the secondary method (.ravel()) down perfectly. Both do the job, though there's a tiny "under the hood" difference: 
* .flatten() always creates a copy  
* .ravel() tries to give you a view (which is faster and saves memory).


## The "Real World" Graduation Challenge

In Data Science, 3D arrays often represent Images.
> Dimension 0: Height
> Dimension 1: Width
> Dimension 2: Color Channels (Red, Green, Blue)

The Final Task:
* Imagine you have a 2x2 pixel image where each pixel has 3 color values (R, G, B).
* Create a 3D array of shape (2, 2, 3) filled with zeros.
* Using Broadcasting, set all "Red" values (the first color channel at index 0) to 255.
* Using Slicing, change the bottom-right pixel's "Green" value (index 1) to 128.

Hint:
* To target all pixels' Red channel: image[:, :, 0] = ...
* To target one specific pixel: image[row, col, channel] = ...


In [38]:
# Setting All to Red Using Broadcasting
img = np.zeros(shape=(2,2,3), dtype=int)
red = [255,0,0]
img +=  red
print(img)

[[[255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]]]


In [39]:
# Using Slicing changing the bottom-right pixel to Green (128)
img[1,1,1] = 128
print(img)

[[[255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255 128   0]]]
